/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.flexibook.application;

import ca.mcgill.ecse.flexibook.model.FlexiBook;
import ca.mcgill.ecse.flexibook.model.User;

public class FlexiBookApplication {
   private static FlexiBook flexibook = new FlexiBook();
   private static User currentUser = null;
   
   public static void main(String args) {
	   
   }
    
    public static FlexiBook getFlexibook() {
    	if (flexibook == null) flexibook = new FlexiBook();
    	return flexibook;
    			
    }
    
    public static User getCurrentUser() {
    	return currentUser;
    }
    
    public static void setCurrentUser(User user) {
    	currentUser = user;
    }
}
